### ISSUE TITLE
携程面试准备

### ISSUE THREAD

**Issue by zonglang** [zonglang/code#10]
> [面试题来源](https://juejin.im/post/5c455a62f265da612415ba90)
## 移动端适配
[前端移动端适配总结](https://juejin.im/entry/59e70320f265da431c6f6514)

## rem和em的区别

* **px**在缩放页面时无法调整那些使用它作为单位的字体
* **em**的值并不是固定，会继承父级元素的字体大小，代表倍数
* **rem**的值并不是固定的，始终是基于根元素懂得，代表倍数

## css画三角形
``` css
#triangle{
    width: 0;
    height: 0;
    border-top: 50px solid blue;
    border-right: 50px solid red;
    border-bottom: 50px solid green;
    border-left: 50px solid yellow;
}
```

##
